# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2016-10-19 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_squashed_0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ladder',
            name='tier',
            field=models.IntegerField(default=0),
        ),
    ]
