# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-24 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ladder_tier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cache',
            name='bid',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cache',
            name='created',
            field=models.DateTimeField(),
        ),
        migrations.AlterIndexTogether(
            name='cache',
            index_together=set([('bid', 'region', 'type')]),
        ),
    ]
