# Generated by Django 2.2.9 on 2020-01-07 12:31

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_changed_to_foreign_key_cascade'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_seen',
            field=models.DateField(default='2019-12-16'),
        ),
        migrations.AddField(
            model_name='team',
            name='last_seen',
            field=models.DateField(default='2019-12-16'),
        ),
        migrations.AlterModelManagers(
            name='player',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='team',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),

    ]
